### ISSUE TITLE
能否提供各布局的get() 方法?

### ISSUE THREAD

**Issue by ljf1172361058** [czy1121/loadinglayout#1]
考虑到需要对自定义布局中的某些控件设置监听,改变样式之类的,希望官方能够提供该方法

**Comment by ljf1172361058** [comment]
或者可以把源码中的 mLayouts 的修饰符改为public也行

**Comment by czy1121** [comment]
布局在showXX时才会inflate
inflate后才可通过findViewById获取对应的View
暴露mLayouts没有必要

**Comment by czy1121** [comment]
目前已添加 `setOnEmptyInflateListener`,`setOnErrorInflateListener` 可确保在自定义布局inflate后设置监听/样式

**Comment by ljf1172361058** [comment]
@多谢.

**Comment by ljf1172361058** [comment]
@czy1121 多谢了.
