### ISSUE TITLE
调用wrap(View view)方法不显示视图

### ISSUE THREAD

**Issue by GhRyuJin** [czy1121/loadinglayout#3]
我在viewpager中的fragment里面用的wrap(View view)方法，我的fragment布局就swiperefreshlayout包裹一个recycleView，然后我在onCreateView里面将recycleView传入了wrap(View view)里面，最后return了swiperefreshlayout，但是页面什么也没有显示，就只有swiperefreshlayout的效果

**Comment by czy1121** [comment]
不明白 "最后return了swiperefreshlayout"，LoadingLayout.wrap返回的是LoadingLayout类型

wrap后有没有调用showXX？

我这边使用正常

**Comment by GhRyuJin** [comment]
我Fragment的布局结构如下：
```
<SwipeRefreshLayout >
     <ListView />
 </SwipeRefreshLayout>
```
然后我用LoadingLayout.wrap(View view)方法传入了ListView,在onCreateView最后returnSwipeRefreshLayout，调用了showXXX方法了，但是还是没有效果，我的Fragment是Viewpager中的一个子项，我开始用的LoadingLayout.wrap(Fragment fragment)直接传入了fragment，但是在该方法中的fragment.getParent()返回了null崩溃，所以用了上一个方法

**Comment by czy1121** [comment]
LoadingLayout.wrap(Fragment fragment) 实际上是`wrap(fragment.getView())`
传入的view必须已经添加到布局中，也就是view.getParent()不能为null

你可以看下wrap源码，代码并不多

我在demo里添加了SwipeRefreshLayout+RecyclerView的例子，你试试看

**Comment by GhRyuJin** [comment]
谢谢了，我看过源码的，直接使用swiperefreshlayout+RecyclerView应该是没有问题的，我的fragment是在viewpager里面的，这样貌似就有问题了哦

**Comment by wss991** [comment]
是有这个问题的，在Viewpager中使用，就显示不出来，我觉得可能是viewpager的预加载的原因造成的

**Comment by yaozhengzheng** [comment]
我的是用的 swiperefreshlayout+listview，有多天数据的时候无法上下滑动，跟上啦加载，下啦刷新冲突了，可是demo上的不冲突，为啥
