### ISSUE TITLE
BaseActivity里面做统一设置应该传什么呢

### ISSUE THREAD

**Issue by Blizzard-liu** [czy1121/loadinglayout#6]

**Comment by czy1121** [comment]
看看wrap函数就明白了啊，wrap函数需要在activity.setContentView后调用

**Comment by Blizzard-liu** [comment]
你 的意思是要在基类写个抽象方法让子类完成布局后在 wrap

**Comment by czy1121** [comment]
**wrap函数要求传入的view已经有parent**,具体你怎么做都可以,比如重载setContentView
